# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4wSWH0xRI8pa5CfUUakK4Wo30Fj4-Xm
"""

pip install opencv-python

import cv2
from google.colab import files
from matplotlib import pyplot as plt

# Foydalanuvchidan rasm yuklash
uploaded = files.upload()

# Yuklangan fayl nomini olish
for file_name in uploaded.keys():
    image_path = file_name

# Rasmni o‘qish
img = cv2.imread(image_path)

# Grayscale formatga o‘tkazamiz
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Haar cascade modeli
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

# Yuzlarni aniqlash
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

# Yuzlar atrofini chizish
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

# Natijani ko‘rsatish
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()